[package]
name = "cargo-play"
version = "0.1.1"
authors = ["Zeyi Fan <cargo@zeyi.fan>"]
edition = "2018"
description = "Run your Rust code file without manually setting up a Cargo project."
license = "MIT"
homepage = "https://github.com/fanzeyi/cargo-play"
readme = "README.md"
categories = ["development-tools::build-utils", "development-tools::cargo-plugins"]

[dependencies]
structopt = "0.2"
failure = "0.1"
toml = "0.5"
sha1 = "0.6"
base64 = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
pathdiff = "0.1.0"
